site_name: "<span style='color:#5dc0cf'>FIWARE<br/>Legal</span>"
site_url: https://fiware-legal.readthedocs.org
repo_url: https://github.com/depa02/FIWARE-Legal
site_description: FIWARE Legal documents
docs_dir: docs
site_dir: html
use_directory_urls: false
theme: readthedocs
# google_analytics: ["UA-*-1", "fiware-legal.readthedocs.io"]
extra_css: ["https://www.fiware.org/style/fiware_readthedocs.css", "https://www.fiware.org/style/fiware_readthedocs_neutral.css"]
pages:
  - Legal: "index.md"
      - "FIWARE Cookies Policy": "FIWARECookiesPolicy.md"
      - "FIWARE Lab Terms & Conditions": "FIWARELabTermsAndConditions.md"
      - "FIWARE Personal Data Protection Policy": "PersonalDataProtection.md"
